apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: photo-gallery-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: photo-gallery-backend
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 15