apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: photo-gallery-backend
  name: photo-gallery-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-gallery-backend
  template:
    metadata:
      labels:
        app: photo-gallery-backend
        tier: backend
    spec:
      containers:
        - image: gitlab.se.ifmo.ru:5050/maria_git/photo_gallery_backend:latest
          name: backend
          resources:
            requests:
              memory: "100Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1"
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
