apiVersion: v1
kind: Service
metadata:
  name: photo-gallery-frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
  selector:
    app: photo-gallery-frontend
    tier: frontend